"""
Deviours Auction — Recommendation Report Generator
Produces a per-bidder Markdown report with score breakdown,
dimension analysis, matched upcoming lots, and recommendation justification.
"""
from __future__ import annotations

import json
from pathlib import Path

from .models import EvaluationResult, PriceBandTrajectory, Recommendation


# Emoji indicators
_REC_ICON = {
    Recommendation.APPROVE: "✅",
    Recommendation.REVIEW:  "🟡",
    Recommendation.REJECT:  "❌",
}

_TRAJ_LABEL = {
    PriceBandTrajectory.UP:       "↑ Escalating (growing collector)",
    PriceBandTrajectory.DOWN:     "↓ Declining (budget-constrained)",
    PriceBandTrajectory.ECLECTIC: "~ Eclectic (varied price bands)",
    PriceBandTrajectory.UNKNOWN:  "? Unknown (insufficient data)",
}


def generate_markdown_report(result: EvaluationResult) -> str:
    """Generate a full Markdown report for one bidder evaluation result."""
    b  = result.breakdown
    rec_icon = _REC_ICON[result.recommendation]
    rec_label = result.recommendation.value.upper()

    lines = [
        f"# Bidder Evaluation Report",
        f"",
        f"**Bidder:** {result.bidder_name}  ",
        f"**Email:** {result.bidder_email}  ",
        f"**Evaluated:** {result.evaluated_at[:10]}  ",
        f"",
        f"---",
        f"",
        f"## {rec_icon} Recommendation: {rec_label}",
        f"",
        f"**Final Score:** {result.score:.2f} / 1.00",
        f"",
        _score_bar(result.score),
        f"",
        f"> Approve ≥ 0.70 · Review 0.40–0.69 · Reject < 0.40",
        f"",
        f"---",
        f"",
        f"## Score Breakdown",
        f"",
        f"| Dimension | Score | Detail |",
        f"|-----------|-------|--------|",
        f"| Win / Loss Rate         | {b.win_loss_rate:.2f} | {b.total_wins} wins from {b.total_bids} bids ({_pct(b.total_wins, b.total_bids)}) |",
        f"| Bid Count (12 months)   | {b.bid_count:.2f} | {b.total_bids} total bids recorded |",
        f"| Reserve Ratio           | {b.reserve_ratio:.2f} | {b.bids_above_reserve}/{b.total_bids} bids met reserve price |",
        f"| Repeat Buyer            | {b.repeat_buyer:.2f} | {b.distinct_lots_won} distinct lots won |",
        f"| Price Band Trajectory   | {b.price_band_trajectory:.2f} | {_TRAJ_LABEL.get(b.trajectory, '?')} |",
        f"| Hammer Price Influence  | {b.hammer_influence:.2f} | Performance above estimate when winning |",
        f"",
    ]

    if b.insufficient_history:
        lines += [
            f"⚠️ **Note:** Fewer than 5 bids on record — scores are provisional.",
            f"",
        ]

    if result.rejection_reasons:
        lines += [
            f"## Flags",
            f"",
        ]
        for r in result.rejection_reasons:
            lines.append(f"- ⚠️ {r}")
        lines.append("")

    if result.matched_lots:
        lines += [
            f"---",
            f"",
            f"## Matched Upcoming Lots",
            f"",
            f"The following upcoming lots match this bidder's historical price bands and preferences:",
            f"",
        ]
        for lot in result.matched_lots:
            lines += [
                f"### {lot.title}",
                f"- **Lot ID:** {lot.lot_id}",
                f"- **Category:** {lot.category}",
                f"- **Estimate:** €{lot.estimate_low:,.0f} – €{lot.estimate_high:,.0f}",
                f"- **Auction Date:** {lot.auction_date[:10]}",
                f"- **Match Reason:** {lot.match_reason}",
                f"",
            ]
    else:
        lines += [
            f"",
            f"*No upcoming lots matched this bidder's price band profile.*",
            f"",
        ]

    lines += [
        f"---",
        f"*Report generated by Deviours Auction Bidder Evaluation Pipeline — Cimelium Ltd*",
    ]
    return "\n".join(lines)


def generate_all_reports(
    results: list[EvaluationResult],
    output_dir: str | Path,
) -> list[Path]:
    """
    Write one Markdown report per bidder to output_dir.
    Returns list of written file paths.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for r in results:
        safe_name = r.bidder_id.lower().replace("/", "-")
        path = out / f"report_{safe_name}.md"
        path.write_text(generate_markdown_report(r), encoding="utf-8")
        written.append(path)
    return written


def generate_summary_table(results: list[EvaluationResult]) -> str:
    """Generate a concise Markdown summary table for all bidders."""
    lines = [
        "# Deviours Auction — Bidder Evaluation Summary",
        "",
        f"**Total bidders evaluated:** {len(results)}",
        f"**Approved:** {sum(1 for r in results if r.recommendation.value == 'approve')}  "
        f"**Review:** {sum(1 for r in results if r.recommendation.value == 'review')}  "
        f"**Rejected:** {sum(1 for r in results if r.recommendation.value == 'reject')}",
        "",
        "| # | Bidder | Score | Recommendation | Bids | Wins | Trajectory |",
        "|---|--------|-------|----------------|------|------|------------|",
    ]
    for i, r in enumerate(results, 1):
        b = r.breakdown
        icon = _REC_ICON[r.recommendation]
        traj = b.trajectory.value if b.trajectory else "?"
        lines.append(
            f"| {i} | {r.bidder_name} | {r.score:.2f} | {icon} {r.recommendation.value.title()} "
            f"| {b.total_bids} | {b.total_wins} | {traj} |"
        )
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _pct(n: int, d: int) -> str:
    return f"{n/d*100:.0f}%" if d else "N/A"


def _score_bar(score: float, width: int = 20) -> str:
    filled = round(score * width)
    bar = "█" * filled + "░" * (width - filled)
    return f"`[{bar}]` {score*100:.0f}%"
