{
    'name': 'SOR Asset Paradigm — Artwork',
    'version': '19.0.1.0.2',
    'author': 'BL',
    'license': 'LGPL-3',
    'category': 'Hidden/Technical',
    'depends': ['sor_asset_paradigm', 'sor_artwork'],
    'data': [
        'security/ir.model.access.csv',
        'data/paradigm_rules_data.xml',
        'data/paradigm_rule_manifestations_data.xml',
        'data/replenish_action_data.xml',
        'views/product_template_views.xml',
        'views/product_views.xml',
    ],
    'application': False,
    'auto_install': True,
    'installable': True,
    'post_init_hook': 'post_init_hook',
}
